import type { Metadata } from 'next'
import { Satisfy } from 'next/font/google'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'

import { Navbar } from '@/components/navbar'

import { cx } from 'class-variance-authority'
import { ThemeProvider } from '@/components/theme-provider'

import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const satisfy = Satisfy({
  variable: '--font-satisfy',
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      className={cx(GeistSans.variable, GeistMono.variable, satisfy.variable)}
    >
      <body className='antialiased dark:text-foreground/90 noise-filter'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <main className='mx-auto flex min-h-screen max-w-2xl flex-col flex-wrap gap-10 px-6 md:py-12 py-8 md:gap-16'>
            <Navbar />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
