import type { Metadata } from 'next'
import { Rock_Salt, Newsreader } from 'next/font/google'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'

import { Navbar } from '@/components/navbar'

import { cx } from 'class-variance-authority'
import { ThemeProvider } from '@/components/theme-provider'

import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RockSalt = Rock_Salt({
  variable: '--font-rocksalt',
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
})
const NewsReader = Newsreader({
  variable: '--font-newsreader',
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      className={cx(
        GeistSans.variable,
        GeistMono.variable,
        RockSalt.variable,
        NewsReader.variable
      )}
    >
      <body className='antialiased dark:text-foreground/90'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <main className='mx-auto flex min-h-screen max-w-3xl flex-col flex-wrap gap-10 px-6 md:py-12 py-8 md:gap-16'>
            <Navbar />
            {children}
            <footer className='w-full max-w-3xl mx-auto pt-12 pb-4'>
              <div className='mb-4 flex flex-wrap gap-x-6 gap-y-1'>
                <a
                  className='font-serif hover:underline hover:underline-offset-2'
                  href='/about'
                >
                  About
                </a>
                <a
                  className='font-serif hover:underline hover:underline-offset-2'
                  href='/contact'
                >
                  Contact
                </a>
                <a
                  className='font-serif hover:underline hover:underline-offset-2'
                  href='/terms'
                >
                  Terms
                </a>
                <a
                  className='font-serif hover:underline hover:underline-offset-2'
                  href='https://github.com/JustGoodUI/dante-astro-theme'
                >
                  Download theme
                </a>
              </div>
              <div className='pt-6 flex flex-col gap-4 border-t border-dashed border-neutral-500 sm:flex-row-reverse sm:justify-between sm:items-center'>
                <div className='flex flex-wrap gap-x-4 gap-y-1'>
                  <a
                    className='inline-flex items-center justify-center text-sm hover:underline hover:underline-offset-2'
                    href='https://dribbble.com/'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    Dribbble
                  </a>
                  <a
                    className='inline-flex items-center justify-center text-sm hover:underline hover:underline-offset-2'
                    href='https://instagram.com/'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    Instagram
                  </a>
                  <a
                    className='inline-flex items-center justify-center text-sm hover:underline hover:underline-offset-2'
                    href='https://twitter.com/'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    X/Twitter
                  </a>
                </div>
                <p className='text-sm'>
                  © 2024&nbsp;
                  <a
                    className='hover:underline hover:underline-offset-2'
                    href='/'
                  >
                    Dante
                  </a>
                  . All rights reserved.
                </p>
              </div>
            </footer>
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
